name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - run: npm install -g @vue/cli
      - name: Use Node.js ${{ matrix.node-version }}
        working-directory: ./displayapp
        run: npm run build
